[build]
  command = "NEXT_DISABLE_ESLINT=1 TURBO_FORCE=1 NEXT_PRIVATE_IGNORE_TYPE_CHECKING=1 npm run build"
  publish = "out" # Adjust based on your setup

[build.environment]
  NEXT_DISABLE_ESLINT = "1"
  TURBO_FORCE = "1"
  NEXT_PRIVATE_IGNORE_TYPE_CHECKING = "1"